#########################################################################
# ⭐⭐⭐  Set parameters carefully for satisfied performance!   ⭐⭐⭐ #
#########################################################################

mass        : 1.2 # kg 
gra         : 9.81 
pose_solver : 1     # 0:来自ZhepeiWang（阻力和更少的奇异性）1:来自ZhepeiWang, 2:来自rotor-drag     
ctrl_freq_max   : 100.0
use_bodyrate_ctrl: false
max_manual_vel: 1.0
max_angle: 30  # 姿态角度限制（单位：度）。负值表示没有限制。
low_voltage: 13.2 # 4S battery

rc_reverse: 
    roll: false
    pitch: false
    yaw: false
    throttle: false

auto_takeoff_land:
    enable: true
    enable_auto_arm: true
    no_RC: false
    takeoff_height: 1.0 # m
    takeoff_land_speed: 0.3 # m/s

thrust_model: # 将推力信号u(0~1)映射到实际推力F（单位：牛顿）的模型：F=K1*Voltage^K2*(K3*u^2+(1-K3)*u)。
    print_value: false # 在推力模型估计期间显示“thr_scale_compensate”或“hover_percentage”的值。
    accurate_thrust_model: false  # 如果不需要精确的控制性能，可以始终启用此选项 :-)
    # 精确推力映射参数
    K1: 0.7583 # 需要精确校准！
    K2: 1.6942 # Needs precise calibration!
    K3: 0.6786 # Needs precise calibration! K3 equals THR_MDL_FAC in https://docs.px4.io/master/en/config_mc/pid_tuning_guide_multicopter.html.
    # 近似推力映射参数
    hover_percentage: 0.30  # 稳定/弧度模式下的推力百分比 # 

gain: 
    # 级联PID控制器。建议阅读代码。
    Kp0: 1.5
    Kp1: 1.5 
    Kp2: 1.5
    Kv0: 1.5
    Kv1: 1.5
    Kv2: 1.5
    # ↓↓↓ No use now --
    Kvi0: 0.0
    Kvi1: 0.0
    Kvi2: 0.0
    Kvd0: 0.0
    Kvd1: 0.0
    Kvd2: 0.0
    # ↓↓↓ 仅在速率控制模式下使用。
    KAngR: 20.0
    KAngP: 20.0
    KAngY: 20.0

rotor_drag:  
    x: 0.0  # The reduced acceleration on each axis caused by rotor drag. Unit:(m*s^-2)/(m*s^-1).
    y: 0.0  # Same as above
    z: 0.0  # Same as above
    k_thrust_horz: 0.0 # Set to 0 recommended... --

msg_timeout:
    odom: 0.5
    rc:   0.5
    cmd:  0.5
    imu:  0.5
    bat:  0.5
