// Generated by gencpp from file traj_utils/LandGroup.msg
// DO NOT EDIT!


#ifndef TRAJ_UTILS_MESSAGE_LANDGROUP_H
#define TRAJ_UTILS_MESSAGE_LANDGROUP_H

#include <ros/service_traits.h>


#include <traj_utils/LandGroupRequest.h>
#include <traj_utils/LandGroupResponse.h>


namespace traj_utils
{

struct LandGroup
{

typedef LandGroupRequest Request;
typedef LandGroupResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LandGroup
} // namespace traj_utils


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::traj_utils::LandGroup > {
  static const char* value()
  {
    return "1c93c56d4ef2aa094d01d2de52397e67";
  }

  static const char* value(const ::traj_utils::LandGroup&) { return value(); }
};

template<>
struct DataType< ::traj_utils::LandGroup > {
  static const char* value()
  {
    return "traj_utils/LandGroup";
  }

  static const char* value(const ::traj_utils::LandGroup&) { return value(); }
};


// service_traits::MD5Sum< ::traj_utils::LandGroupRequest> should match
// service_traits::MD5Sum< ::traj_utils::LandGroup >
template<>
struct MD5Sum< ::traj_utils::LandGroupRequest>
{
  static const char* value()
  {
    return MD5Sum< ::traj_utils::LandGroup >::value();
  }
  static const char* value(const ::traj_utils::LandGroupRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::traj_utils::LandGroupRequest> should match
// service_traits::DataType< ::traj_utils::LandGroup >
template<>
struct DataType< ::traj_utils::LandGroupRequest>
{
  static const char* value()
  {
    return DataType< ::traj_utils::LandGroup >::value();
  }
  static const char* value(const ::traj_utils::LandGroupRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::traj_utils::LandGroupResponse> should match
// service_traits::MD5Sum< ::traj_utils::LandGroup >
template<>
struct MD5Sum< ::traj_utils::LandGroupResponse>
{
  static const char* value()
  {
    return MD5Sum< ::traj_utils::LandGroup >::value();
  }
  static const char* value(const ::traj_utils::LandGroupResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::traj_utils::LandGroupResponse> should match
// service_traits::DataType< ::traj_utils::LandGroup >
template<>
struct DataType< ::traj_utils::LandGroupResponse>
{
  static const char* value()
  {
    return DataType< ::traj_utils::LandGroup >::value();
  }
  static const char* value(const ::traj_utils::LandGroupResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TRAJ_UTILS_MESSAGE_LANDGROUP_H
