// Generated by gencpp from file traj_utils/Reset.msg
// DO NOT EDIT!


#ifndef TRAJ_UTILS_MESSAGE_RESET_H
#define TRAJ_UTILS_MESSAGE_RESET_H

#include <ros/service_traits.h>


#include <traj_utils/ResetRequest.h>
#include <traj_utils/ResetResponse.h>


namespace traj_utils
{

struct Reset
{

typedef ResetRequest Request;
typedef ResetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Reset
} // namespace traj_utils


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::traj_utils::Reset > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::traj_utils::Reset&) { return value(); }
};

template<>
struct DataType< ::traj_utils::Reset > {
  static const char* value()
  {
    return "traj_utils/Reset";
  }

  static const char* value(const ::traj_utils::Reset&) { return value(); }
};


// service_traits::MD5Sum< ::traj_utils::ResetRequest> should match
// service_traits::MD5Sum< ::traj_utils::Reset >
template<>
struct MD5Sum< ::traj_utils::ResetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::traj_utils::Reset >::value();
  }
  static const char* value(const ::traj_utils::ResetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::traj_utils::ResetRequest> should match
// service_traits::DataType< ::traj_utils::Reset >
template<>
struct DataType< ::traj_utils::ResetRequest>
{
  static const char* value()
  {
    return DataType< ::traj_utils::Reset >::value();
  }
  static const char* value(const ::traj_utils::ResetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::traj_utils::ResetResponse> should match
// service_traits::MD5Sum< ::traj_utils::Reset >
template<>
struct MD5Sum< ::traj_utils::ResetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::traj_utils::Reset >::value();
  }
  static const char* value(const ::traj_utils::ResetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::traj_utils::ResetResponse> should match
// service_traits::DataType< ::traj_utils::Reset >
template<>
struct DataType< ::traj_utils::ResetResponse>
{
  static const char* value()
  {
    return DataType< ::traj_utils::Reset >::value();
  }
  static const char* value(const ::traj_utils::ResetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TRAJ_UTILS_MESSAGE_RESET_H
