// Generated by gencpp from file traj_utils/SetGPSPosition.msg
// DO NOT EDIT!


#ifndef TRAJ_UTILS_MESSAGE_SETGPSPOSITION_H
#define TRAJ_UTILS_MESSAGE_SETGPSPOSITION_H

#include <ros/service_traits.h>


#include <traj_utils/SetGPSPositionRequest.h>
#include <traj_utils/SetGPSPositionResponse.h>


namespace traj_utils
{

struct SetGPSPosition
{

typedef SetGPSPositionRequest Request;
typedef SetGPSPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetGPSPosition
} // namespace traj_utils


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::traj_utils::SetGPSPosition > {
  static const char* value()
  {
    return "419da4302dcfe39986b1a614149a1599";
  }

  static const char* value(const ::traj_utils::SetGPSPosition&) { return value(); }
};

template<>
struct DataType< ::traj_utils::SetGPSPosition > {
  static const char* value()
  {
    return "traj_utils/SetGPSPosition";
  }

  static const char* value(const ::traj_utils::SetGPSPosition&) { return value(); }
};


// service_traits::MD5Sum< ::traj_utils::SetGPSPositionRequest> should match
// service_traits::MD5Sum< ::traj_utils::SetGPSPosition >
template<>
struct MD5Sum< ::traj_utils::SetGPSPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::traj_utils::SetGPSPosition >::value();
  }
  static const char* value(const ::traj_utils::SetGPSPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::traj_utils::SetGPSPositionRequest> should match
// service_traits::DataType< ::traj_utils::SetGPSPosition >
template<>
struct DataType< ::traj_utils::SetGPSPositionRequest>
{
  static const char* value()
  {
    return DataType< ::traj_utils::SetGPSPosition >::value();
  }
  static const char* value(const ::traj_utils::SetGPSPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::traj_utils::SetGPSPositionResponse> should match
// service_traits::MD5Sum< ::traj_utils::SetGPSPosition >
template<>
struct MD5Sum< ::traj_utils::SetGPSPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::traj_utils::SetGPSPosition >::value();
  }
  static const char* value(const ::traj_utils::SetGPSPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::traj_utils::SetGPSPositionResponse> should match
// service_traits::DataType< ::traj_utils::SetGPSPosition >
template<>
struct DataType< ::traj_utils::SetGPSPositionResponse>
{
  static const char* value()
  {
    return DataType< ::traj_utils::SetGPSPosition >::value();
  }
  static const char* value(const ::traj_utils::SetGPSPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TRAJ_UTILS_MESSAGE_SETGPSPOSITION_H
