// Generated by gencpp from file traj_utils/SetLocalPosition.msg
// DO NOT EDIT!


#ifndef TRAJ_UTILS_MESSAGE_SETLOCALPOSITION_H
#define TRAJ_UTILS_MESSAGE_SETLOCALPOSITION_H

#include <ros/service_traits.h>


#include <traj_utils/SetLocalPositionRequest.h>
#include <traj_utils/SetLocalPositionResponse.h>


namespace traj_utils
{

struct SetLocalPosition
{

typedef SetLocalPositionRequest Request;
typedef SetLocalPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetLocalPosition
} // namespace traj_utils


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::traj_utils::SetLocalPosition > {
  static const char* value()
  {
    return "23cc107c6db5068a5234b2dfe0bcf0bb";
  }

  static const char* value(const ::traj_utils::SetLocalPosition&) { return value(); }
};

template<>
struct DataType< ::traj_utils::SetLocalPosition > {
  static const char* value()
  {
    return "traj_utils/SetLocalPosition";
  }

  static const char* value(const ::traj_utils::SetLocalPosition&) { return value(); }
};


// service_traits::MD5Sum< ::traj_utils::SetLocalPositionRequest> should match
// service_traits::MD5Sum< ::traj_utils::SetLocalPosition >
template<>
struct MD5Sum< ::traj_utils::SetLocalPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::traj_utils::SetLocalPosition >::value();
  }
  static const char* value(const ::traj_utils::SetLocalPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::traj_utils::SetLocalPositionRequest> should match
// service_traits::DataType< ::traj_utils::SetLocalPosition >
template<>
struct DataType< ::traj_utils::SetLocalPositionRequest>
{
  static const char* value()
  {
    return DataType< ::traj_utils::SetLocalPosition >::value();
  }
  static const char* value(const ::traj_utils::SetLocalPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::traj_utils::SetLocalPositionResponse> should match
// service_traits::MD5Sum< ::traj_utils::SetLocalPosition >
template<>
struct MD5Sum< ::traj_utils::SetLocalPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::traj_utils::SetLocalPosition >::value();
  }
  static const char* value(const ::traj_utils::SetLocalPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::traj_utils::SetLocalPositionResponse> should match
// service_traits::DataType< ::traj_utils::SetLocalPosition >
template<>
struct DataType< ::traj_utils::SetLocalPositionResponse>
{
  static const char* value()
  {
    return DataType< ::traj_utils::SetLocalPosition >::value();
  }
  static const char* value(const ::traj_utils::SetLocalPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TRAJ_UTILS_MESSAGE_SETLOCALPOSITION_H
