// Generated by gencpp from file traj_utils/TopicHz.msg
// DO NOT EDIT!


#ifndef TRAJ_UTILS_MESSAGE_TOPICHZ_H
#define TRAJ_UTILS_MESSAGE_TOPICHZ_H

#include <ros/service_traits.h>


#include <traj_utils/TopicHzRequest.h>
#include <traj_utils/TopicHzResponse.h>


namespace traj_utils
{

struct TopicHz
{

typedef TopicHzRequest Request;
typedef TopicHzResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TopicHz
} // namespace traj_utils


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::traj_utils::TopicHz > {
  static const char* value()
  {
    return "be220a7e84277b3c72a3145179becfe7";
  }

  static const char* value(const ::traj_utils::TopicHz&) { return value(); }
};

template<>
struct DataType< ::traj_utils::TopicHz > {
  static const char* value()
  {
    return "traj_utils/TopicHz";
  }

  static const char* value(const ::traj_utils::TopicHz&) { return value(); }
};


// service_traits::MD5Sum< ::traj_utils::TopicHzRequest> should match
// service_traits::MD5Sum< ::traj_utils::TopicHz >
template<>
struct MD5Sum< ::traj_utils::TopicHzRequest>
{
  static const char* value()
  {
    return MD5Sum< ::traj_utils::TopicHz >::value();
  }
  static const char* value(const ::traj_utils::TopicHzRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::traj_utils::TopicHzRequest> should match
// service_traits::DataType< ::traj_utils::TopicHz >
template<>
struct DataType< ::traj_utils::TopicHzRequest>
{
  static const char* value()
  {
    return DataType< ::traj_utils::TopicHz >::value();
  }
  static const char* value(const ::traj_utils::TopicHzRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::traj_utils::TopicHzResponse> should match
// service_traits::MD5Sum< ::traj_utils::TopicHz >
template<>
struct MD5Sum< ::traj_utils::TopicHzResponse>
{
  static const char* value()
  {
    return MD5Sum< ::traj_utils::TopicHz >::value();
  }
  static const char* value(const ::traj_utils::TopicHzResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::traj_utils::TopicHzResponse> should match
// service_traits::DataType< ::traj_utils::TopicHz >
template<>
struct DataType< ::traj_utils::TopicHzResponse>
{
  static const char* value()
  {
    return DataType< ::traj_utils::TopicHz >::value();
  }
  static const char* value(const ::traj_utils::TopicHzResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TRAJ_UTILS_MESSAGE_TOPICHZ_H
