// Generated by gencpp from file traj_utils/Circle.msg
// DO NOT EDIT!


#ifndef TRAJ_UTILS_MESSAGE_CIRCLE_H
#define TRAJ_UTILS_MESSAGE_CIRCLE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Vector3.h>

namespace traj_utils
{
template <class ContainerAllocator>
struct Circle_
{
  typedef Circle_<ContainerAllocator> Type;

  Circle_()
    : index(0)
    , position()
    , yaw(0.0)  {
    }
  Circle_(const ContainerAllocator& _alloc)
    : index(0)
    , position(_alloc)
    , yaw(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _index_type;
  _index_type index;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef double _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::traj_utils::Circle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::traj_utils::Circle_<ContainerAllocator> const> ConstPtr;

}; // struct Circle_

typedef ::traj_utils::Circle_<std::allocator<void> > Circle;

typedef boost::shared_ptr< ::traj_utils::Circle > CirclePtr;
typedef boost::shared_ptr< ::traj_utils::Circle const> CircleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::traj_utils::Circle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::traj_utils::Circle_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::traj_utils::Circle_<ContainerAllocator1> & lhs, const ::traj_utils::Circle_<ContainerAllocator2> & rhs)
{
  return lhs.index == rhs.index &&
    lhs.position == rhs.position &&
    lhs.yaw == rhs.yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::traj_utils::Circle_<ContainerAllocator1> & lhs, const ::traj_utils::Circle_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace traj_utils

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::traj_utils::Circle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::traj_utils::Circle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::traj_utils::Circle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::traj_utils::Circle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::traj_utils::Circle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::traj_utils::Circle_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::traj_utils::Circle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "182de38a68dfb7440273ce21ac6bad6d";
  }

  static const char* value(const ::traj_utils::Circle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x182de38a68dfb744ULL;
  static const uint64_t static_value2 = 0x0273ce21ac6bad6dULL;
};

template<class ContainerAllocator>
struct DataType< ::traj_utils::Circle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "traj_utils/Circle";
  }

  static const char* value(const ::traj_utils::Circle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::traj_utils::Circle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 index\n"
"geometry_msgs/Vector3 position\n"
"float64 yaw\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::traj_utils::Circle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::traj_utils::Circle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.index);
      stream.next(m.position);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Circle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::traj_utils::Circle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::traj_utils::Circle_<ContainerAllocator>& v)
  {
    s << indent << "index: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.index);
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRAJ_UTILS_MESSAGE_CIRCLE_H
