// Generated by gencpp from file traj_utils/Land.msg
// DO NOT EDIT!


#ifndef TRAJ_UTILS_MESSAGE_LAND_H
#define TRAJ_UTILS_MESSAGE_LAND_H

#include <ros/service_traits.h>


#include <traj_utils/LandRequest.h>
#include <traj_utils/LandResponse.h>


namespace traj_utils
{

struct Land
{

typedef LandRequest Request;
typedef LandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Land
} // namespace traj_utils


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::traj_utils::Land > {
  static const char* value()
  {
    return "3a122444608b7d9984b24a10fba10ac1";
  }

  static const char* value(const ::traj_utils::Land&) { return value(); }
};

template<>
struct DataType< ::traj_utils::Land > {
  static const char* value()
  {
    return "traj_utils/Land";
  }

  static const char* value(const ::traj_utils::Land&) { return value(); }
};


// service_traits::MD5Sum< ::traj_utils::LandRequest> should match
// service_traits::MD5Sum< ::traj_utils::Land >
template<>
struct MD5Sum< ::traj_utils::LandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::traj_utils::Land >::value();
  }
  static const char* value(const ::traj_utils::LandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::traj_utils::LandRequest> should match
// service_traits::DataType< ::traj_utils::Land >
template<>
struct DataType< ::traj_utils::LandRequest>
{
  static const char* value()
  {
    return DataType< ::traj_utils::Land >::value();
  }
  static const char* value(const ::traj_utils::LandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::traj_utils::LandResponse> should match
// service_traits::MD5Sum< ::traj_utils::Land >
template<>
struct MD5Sum< ::traj_utils::LandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::traj_utils::Land >::value();
  }
  static const char* value(const ::traj_utils::LandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::traj_utils::LandResponse> should match
// service_traits::DataType< ::traj_utils::Land >
template<>
struct DataType< ::traj_utils::LandResponse>
{
  static const char* value()
  {
    return DataType< ::traj_utils::Land >::value();
  }
  static const char* value(const ::traj_utils::LandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TRAJ_UTILS_MESSAGE_LAND_H
