// Generated by gencpp from file traj_utils/TakeoffGroup.msg
// DO NOT EDIT!


#ifndef TRAJ_UTILS_MESSAGE_TAKEOFFGROUP_H
#define TRAJ_UTILS_MESSAGE_TAKEOFFGROUP_H

#include <ros/service_traits.h>


#include <traj_utils/TakeoffGroupRequest.h>
#include <traj_utils/TakeoffGroupResponse.h>


namespace traj_utils
{

struct TakeoffGroup
{

typedef TakeoffGroupRequest Request;
typedef TakeoffGroupResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TakeoffGroup
} // namespace traj_utils


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::traj_utils::TakeoffGroup > {
  static const char* value()
  {
    return "1c93c56d4ef2aa094d01d2de52397e67";
  }

  static const char* value(const ::traj_utils::TakeoffGroup&) { return value(); }
};

template<>
struct DataType< ::traj_utils::TakeoffGroup > {
  static const char* value()
  {
    return "traj_utils/TakeoffGroup";
  }

  static const char* value(const ::traj_utils::TakeoffGroup&) { return value(); }
};


// service_traits::MD5Sum< ::traj_utils::TakeoffGroupRequest> should match
// service_traits::MD5Sum< ::traj_utils::TakeoffGroup >
template<>
struct MD5Sum< ::traj_utils::TakeoffGroupRequest>
{
  static const char* value()
  {
    return MD5Sum< ::traj_utils::TakeoffGroup >::value();
  }
  static const char* value(const ::traj_utils::TakeoffGroupRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::traj_utils::TakeoffGroupRequest> should match
// service_traits::DataType< ::traj_utils::TakeoffGroup >
template<>
struct DataType< ::traj_utils::TakeoffGroupRequest>
{
  static const char* value()
  {
    return DataType< ::traj_utils::TakeoffGroup >::value();
  }
  static const char* value(const ::traj_utils::TakeoffGroupRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::traj_utils::TakeoffGroupResponse> should match
// service_traits::MD5Sum< ::traj_utils::TakeoffGroup >
template<>
struct MD5Sum< ::traj_utils::TakeoffGroupResponse>
{
  static const char* value()
  {
    return MD5Sum< ::traj_utils::TakeoffGroup >::value();
  }
  static const char* value(const ::traj_utils::TakeoffGroupResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::traj_utils::TakeoffGroupResponse> should match
// service_traits::DataType< ::traj_utils::TakeoffGroup >
template<>
struct DataType< ::traj_utils::TakeoffGroupResponse>
{
  static const char* value()
  {
    return DataType< ::traj_utils::TakeoffGroup >::value();
  }
  static const char* value(const ::traj_utils::TakeoffGroupResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TRAJ_UTILS_MESSAGE_TAKEOFFGROUP_H
