// Generated by gencpp from file traj_utils/Takeoff.msg
// DO NOT EDIT!


#ifndef TRAJ_UTILS_MESSAGE_TAKEOFF_H
#define TRAJ_UTILS_MESSAGE_TAKEOFF_H

#include <ros/service_traits.h>


#include <traj_utils/TakeoffRequest.h>
#include <traj_utils/TakeoffResponse.h>


namespace traj_utils
{

struct Takeoff
{

typedef TakeoffRequest Request;
typedef TakeoffResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Takeoff
} // namespace traj_utils


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::traj_utils::Takeoff > {
  static const char* value()
  {
    return "3a122444608b7d9984b24a10fba10ac1";
  }

  static const char* value(const ::traj_utils::Takeoff&) { return value(); }
};

template<>
struct DataType< ::traj_utils::Takeoff > {
  static const char* value()
  {
    return "traj_utils/Takeoff";
  }

  static const char* value(const ::traj_utils::Takeoff&) { return value(); }
};


// service_traits::MD5Sum< ::traj_utils::TakeoffRequest> should match
// service_traits::MD5Sum< ::traj_utils::Takeoff >
template<>
struct MD5Sum< ::traj_utils::TakeoffRequest>
{
  static const char* value()
  {
    return MD5Sum< ::traj_utils::Takeoff >::value();
  }
  static const char* value(const ::traj_utils::TakeoffRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::traj_utils::TakeoffRequest> should match
// service_traits::DataType< ::traj_utils::Takeoff >
template<>
struct DataType< ::traj_utils::TakeoffRequest>
{
  static const char* value()
  {
    return DataType< ::traj_utils::Takeoff >::value();
  }
  static const char* value(const ::traj_utils::TakeoffRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::traj_utils::TakeoffResponse> should match
// service_traits::MD5Sum< ::traj_utils::Takeoff >
template<>
struct MD5Sum< ::traj_utils::TakeoffResponse>
{
  static const char* value()
  {
    return MD5Sum< ::traj_utils::Takeoff >::value();
  }
  static const char* value(const ::traj_utils::TakeoffResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::traj_utils::TakeoffResponse> should match
// service_traits::DataType< ::traj_utils::Takeoff >
template<>
struct DataType< ::traj_utils::TakeoffResponse>
{
  static const char* value()
  {
    return DataType< ::traj_utils::Takeoff >::value();
  }
  static const char* value(const ::traj_utils::TakeoffResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TRAJ_UTILS_MESSAGE_TAKEOFF_H
