// Generated by gencpp from file traj_utils/TakeoffGroupResponse.msg
// DO NOT EDIT!


#ifndef TRAJ_UTILS_MESSAGE_TAKEOFFGROUPRESPONSE_H
#define TRAJ_UTILS_MESSAGE_TAKEOFFGROUPRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace traj_utils
{
template <class ContainerAllocator>
struct TakeoffGroupResponse_
{
  typedef TakeoffGroupResponse_<ContainerAllocator> Type;

  TakeoffGroupResponse_()
    : success(false)  {
    }
  TakeoffGroupResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::traj_utils::TakeoffGroupResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::traj_utils::TakeoffGroupResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TakeoffGroupResponse_

typedef ::traj_utils::TakeoffGroupResponse_<std::allocator<void> > TakeoffGroupResponse;

typedef boost::shared_ptr< ::traj_utils::TakeoffGroupResponse > TakeoffGroupResponsePtr;
typedef boost::shared_ptr< ::traj_utils::TakeoffGroupResponse const> TakeoffGroupResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::traj_utils::TakeoffGroupResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::traj_utils::TakeoffGroupResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::traj_utils::TakeoffGroupResponse_<ContainerAllocator1> & lhs, const ::traj_utils::TakeoffGroupResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::traj_utils::TakeoffGroupResponse_<ContainerAllocator1> & lhs, const ::traj_utils::TakeoffGroupResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace traj_utils

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::traj_utils::TakeoffGroupResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::traj_utils::TakeoffGroupResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::traj_utils::TakeoffGroupResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::traj_utils::TakeoffGroupResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::traj_utils::TakeoffGroupResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::traj_utils::TakeoffGroupResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::traj_utils::TakeoffGroupResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::traj_utils::TakeoffGroupResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::traj_utils::TakeoffGroupResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "traj_utils/TakeoffGroupResponse";
  }

  static const char* value(const ::traj_utils::TakeoffGroupResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::traj_utils::TakeoffGroupResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
;
  }

  static const char* value(const ::traj_utils::TakeoffGroupResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::traj_utils::TakeoffGroupResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TakeoffGroupResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::traj_utils::TakeoffGroupResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::traj_utils::TakeoffGroupResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRAJ_UTILS_MESSAGE_TAKEOFFGROUPRESPONSE_H
